/*----------------------------------------------------------------------------------*/
/* Product:            Visual Data Mining and Machine Learning                      */
/* Release Version:    V2023.10                                                     */
/* Component Version:  V2023.10                                                     */
/* CAS Version:        V.04.00M0P10162023                                           */
/* SAS Version:        V.04.00M0P101623                                             */
/* Site Number:        70180938                                                     */
/* Host:               sas-cas-server-default-client                                */
/* Encoding:           utf-8                                                        */
/* Java Encoding:      UTF8                                                         */
/* Locale:             en_US                                                        */
/* Project GUID:       ffe6ca27-0553-4ff5-b5e3-297186cfa1ae                         */
/* Node GUID:          ab096887-71a3-498a-8acb-c7c658ff67f4                         */
/* Node Id:            A4J0U9C7HSP3T2DROU44DGQNO                                    */
/* Algorithm:          Linear Regression                                            */
/* Generated by:       geldmui@gelenable.sas.com                                    */
/* Date:               13MAR2024:13:09:51                                           */
/*----------------------------------------------------------------------------------*/
package MS_ab09688771a3498a8acbc7c658ff67f4_13MAR2024130951314 / overwrite=yes;
   dcl double "Miles";
   dcl double "P_BlueBookPrice" having label n'Predicted: BlueBookPrice';
   dcl double "EM_PREDICTION";
   varlist allvars [_all_];
 
   method _A4J0U9C7HSP3T2DROU44DGQNO();
      dcl double _J_;
      dcl double _I_;
      dcl double _TEMP_;
      dcl double _LINP_;
      dcl double _BADVAL_;
      dcl nchar(6) _MILES_;
      dcl double _BETA_26481454_0_[14];
      dcl double _XROW_26481454_0_[14];
       
      _BETA_26481454_0_:=(11999.9999999999, 23000, 68000, 16000, 28000, -6999.99999999998,
      -3999.99999999998, 0, 0, 1.6608936448392E-11, -3999.99999999998, 0, 0,
      0);
      _BADVAL_ = 0.0;
      _LINP_ = 0.0;
      _TEMP_ = 0.0;
      _I_ = 0.0;
      _J_ = 0.0;
      _MILES_ = LEFT(TRIM(put(MILES, BEST6.)));
      do _I_ = 1.0 to 14.0;
      _XROW_26481454_0_[_I_] = 0.0;
      end;
      _XROW_26481454_0_[1.0] = 1.0;
      _TEMP_ = 1.0;
      select (_MILES_);
      when ('4000') _XROW_26481454_0_[2.0] = _TEMP_;
      when ('5000') _XROW_26481454_0_[3.0] = _TEMP_;
      when ('20000') _XROW_26481454_0_[4.0] = _TEMP_;
      when ('40000') _XROW_26481454_0_[5.0] = _TEMP_;
      when ('50000') _XROW_26481454_0_[6.0] = _TEMP_;
      when ('59000') _XROW_26481454_0_[7.0] = _TEMP_;
      when ('68000') _XROW_26481454_0_[8.0] = _TEMP_;
      when ('70000') _XROW_26481454_0_[9.0] = _TEMP_;
      when ('80000') _XROW_26481454_0_[10.0] = _TEMP_;
      when ('82000') _XROW_26481454_0_[11.0] = _TEMP_;
      when ('90000') _XROW_26481454_0_[12.0] = _TEMP_;
      when ('100000') _XROW_26481454_0_[13.0] = _TEMP_;
      when ('270000') _XROW_26481454_0_[14.0] = _TEMP_;
      otherwise do ;
      _BADVAL_ = 1.0;
      goto SKIP_26481454_0;
      end;
      end;
      do _I_ = 1.0 to 14.0;
      _LINP_ + _XROW_26481454_0_[_I_] * _BETA_26481454_0_[_I_];
      end;
      SKIP_26481454_0: if (_BADVAL_ = 0.0) & ^MISSING(_LINP_) then do ;
      P_BLUEBOOKPRICE = _LINP_;
      end;
      else do ;
      _LINP_ = .;
      P_BLUEBOOKPRICE = .;
      end;
      if "P_BLUEBOOKPRICE" = . then "P_BLUEBOOKPRICE" = 22142.857143;
      EM_PREDICTION = "P_BLUEBOOKPRICE";
    
   end;
    
 
   method score(
      double "Miles",
      IN_OUT double "EM_PREDICTION",
      IN_OUT double "P_BlueBookPrice"
   );
      this."Miles"= "Miles";
 
      _A4J0U9C7HSP3T2DROU44DGQNO();
 
      "EM_PREDICTION"= this."EM_PREDICTION";
      "P_BlueBookPrice"= this."P_BlueBookPrice";
   end;
 
 
   method predictedscore(
      double "Miles",
      IN_OUT double "EM_PREDICTION",
      IN_OUT double "P_BlueBookPrice"
   );
      this."Miles"= "Miles";
 
      _A4J0U9C7HSP3T2DROU44DGQNO();
 
      "EM_PREDICTION"= this."EM_PREDICTION";
      "P_BlueBookPrice"= this."P_BlueBookPrice";
   end;
 
endpackage;
