/*----------------------------------------------------------------------------------*/
/* Product:            Visual Data Mining and Machine Learning                      */
/* Release Version:    V2023.10                                                     */
/* Component Version:  V2023.10                                                     */
/* CAS Version:        V.04.00M0P10162023                                           */
/* SAS Version:        V.04.00M0P101623                                             */
/* Site Number:        70180938                                                     */
/* Host:               sas-cas-server-default-client                                */
/* Encoding:           utf-8                                                        */
/* Java Encoding:      UTF8                                                         */
/* Locale:             en_US                                                        */
/* Project GUID:       ffe6ca27-0553-4ff5-b5e3-297186cfa1ae                         */
/* Node GUID:          ab096887-71a3-498a-8acb-c7c658ff67f4                         */
/* Node Id:            A4J0U9C7HSP3T2DROU44DGQNO                                    */
/* Algorithm:          Linear Regression                                            */
/* Generated by:       geldmui@gelenable.sas.com                                    */
/* Date:               13MAR2024:13:09:51                                           */
/*----------------------------------------------------------------------------------*/
*------------------------------------------------------------*;
*Nodeid: _JD7R09P04CQH7BE3OG8ESWDZ;
*------------------------------------------------------------*;
*------------------------------------------------------------*;
*Nodeid: _F0W32K6GQ7MS4VZKDBX3YSVLN;
*------------------------------------------------------------*;
*------------------------------------------------------------*;
*Nodeid: _A4J0U9C7HSP3T2DROU44DGQNO;
*------------------------------------------------------------*;
   /*---------------------------------------------------------
     Generated SAS Scoring Code
     Date: 13Mar2024:13:09:50
     -------------------------------------------------------*/

   drop _badval_ _linp_ _temp_ _i_ _j_;
   _badval_ = 0;
   _linp_   = 0;
   _temp_   = 0;
   _i_      = 0;
   _j_      = 0;

   array _xrow_26481454_0_{14} _temporary_;
   array _beta_26481454_0_{14} _temporary_ (    11999.9999999999
                      23000
                      68000
                      16000
                      28000
          -6999.99999999998
          -3999.99999999998
                          0
                          0
        1.6608936448392E-11
          -3999.99999999998
                          0
                          0
                          0);

   length _Miles_ $6; drop _Miles_;
   _Miles_ = left(trim(put(Miles,BEST6.)));
   do _i_=1 to 14; _xrow_26481454_0_{_i_} = 0; end;

   _xrow_26481454_0_[1] = 1;

   _temp_ = 1;
   select (_Miles_);
      when ('4000') _xrow_26481454_0_[2] = _temp_;
      when ('5000') _xrow_26481454_0_[3] = _temp_;
      when ('20000') _xrow_26481454_0_[4] = _temp_;
      when ('40000') _xrow_26481454_0_[5] = _temp_;
      when ('50000') _xrow_26481454_0_[6] = _temp_;
      when ('59000') _xrow_26481454_0_[7] = _temp_;
      when ('68000') _xrow_26481454_0_[8] = _temp_;
      when ('70000') _xrow_26481454_0_[9] = _temp_;
      when ('80000') _xrow_26481454_0_[10] = _temp_;
      when ('82000') _xrow_26481454_0_[11] = _temp_;
      when ('90000') _xrow_26481454_0_[12] = _temp_;
      when ('100000') _xrow_26481454_0_[13] = _temp_;
      when ('270000') _xrow_26481454_0_[14] = _temp_;
      otherwise do; _badval_ = 1; goto skip_26481454_0; end;
   end;

   do _i_=1 to 14;
      _linp_ + _xrow_26481454_0_{_i_} * _beta_26481454_0_{_i_};
   end;

   skip_26481454_0:
   label P_BlueBookPrice = 'Predicted: BlueBookPrice';
   if (_badval_ eq 0) and not missing(_linp_) then do;
      P_BlueBookPrice = _linp_;
   end; else do;
      _linp_ = .;
      P_BlueBookPrice = .;
   end;


   *------------------------------------------------------------*;
   * Accounting for missing predicted variable;
   *------------------------------------------------------------*;
   label "P_BlueBookPrice"n ='Predicted: BlueBookPrice';
   if "P_BlueBookPrice"n = . then "P_BlueBookPrice"n =22142.857143;
*------------------------------------------------------------*;
* Generating fixed output names;
*------------------------------------------------------------*;
Length EM_PREDICTION 8;
LABEL EM_PREDICTION= "Prediction for BlueBookPrice";
EM_PREDICTION= 'P_BlueBookPrice'n;
